type ViewProps={variant:"utility"|"rx"};

const data={
 utility:{stakeholders:[["Customer","Find reports and understand status","Validated navigation and batch visibility"],["Customer Service","Reduce confusion and repeated guidance","Surfaced customer friction and terminology"],["Production","Preserve active report workflow","Defined operational constraints"],["Leadership","Improve a client-facing capability safely","Aligned scope to business value"],["Technical","Maintain platform compatibility","Protected existing structure and links"]],tradeoffs:[["Changed","Search, interactive status filters, language tabs, responsive hierarchy"],["Preserved","Report organization, terminology, links, and production workflow"],["Considered","A full system rebuild with a new content model"],["Deferred","Platform replacement because disruption outweighed the immediate customer value"]],launch:[["QA","Tested search, filters, links, language states, and screen sizes"],["Readiness","Confirmed familiar terminology and unchanged internal workflow"],["Communication","Presented the new navigation and status model to the customer"],["Rollout","Released the interface around the existing live report structure"],["Monitoring","Collected direct customer feedback and checked core workflows"]],metrics:[["Verified","Core report and status workflows remained functional"],["Customer","Customer reported easier batch navigation"],["Operational","Production process remained unchanged"],["Directional","Greater clarity and faster report discovery"],["Future KPI","Search success, task time, support volume, return usage"]],backlog:[["High","Instrument search success and report-click behavior","Establish a measurable usability baseline"],["High","Create a repeatable customer feedback check-in","Turn validation into a consistent signal"],["Medium","Add saved or recent report views","Reduce repeat-customer effort after usage data confirms need"],["Future","Evaluate a scalable reporting platform","Revisit only when volume or maintenance burden justifies migration"]]},
 rx:{stakeholders:[["Healthcare customers","Choose compliant products confidently","Informed guidance and selection design"],["Customer Service","Reduce avoidable ordering questions","Converted recurring calls into content"],["Production","Receive valid, fulfillable orders","Protected configurations and handoffs"],["Compliance","Keep security guidance accurate","Shaped content and QA requirements"],["Leadership / Sales","Capture demand and grow the channel","Connected supplier disruption to acquisition strategy"],["Technical","Preserve 4D logic and maintainability","Constrained implementation scope"]],tradeoffs:[["Changed","Information hierarchy, product comparison, mobile flow, resources"],["Preserved","4D tags, forms, IDs, actions, destinations, and configurations"],["Considered","Rebuilding the order experience on a modern commerce platform"],["Deferred","Backend migration until conversion data and maintenance cost justify it"]],launch:[["QA","Checked all 20 selection paths, forms, links, responsive states, and content"],["Readiness","Preserved fulfillment inputs so production needed no new process"],["Communication","Added clearer timing, security, product, and support guidance"],["Rollout","Modernized connected pages while retaining live order logic"],["Monitoring","Reviewed analytics, inbound calls, orders, and page visibility"]],metrics:[["Verified","1,272% increase in new users in the reported comparison period"],["Operational","20 product-selection paths and the 4D workflow preserved"],["Customer","Inbound calls identified unmet replacement-supplier demand"],["Directional","Orders increased after launch, without configured attribution"],["Future KPI","Conversion, abandonment, article-to-order path, support drivers"]],backlog:[["High","Configure completed-order and funnel events","Connect acquisition growth to conversion"],["High","Track support contacts by question type","Prioritize guidance using operational demand"],["Medium","Test product comparison and repeat-order shortcuts","Improve completion after a baseline exists"],["Future","Evaluate backend modernization","Pursue only when value exceeds migration and compliance risk"]]}
} as const;

export default function ProjectOperatingViews({variant}:ViewProps){const d=data[variant];return <>
 <section className="project-framework shell" id="stakeholders"><div className="section-intro"><p className="kicker">Stakeholder map</p><h2>Alignment shaped the solution.</h2><p>Each group entered the work when its goals, constraints, or evidence could influence the outcome.</p></div><div className="project-stakeholders">{d.stakeholders.map(([name,goal,influence])=><article key={name}><h3>{name}</h3><p>{goal}</p><span>{influence}</span></article>)}</div></section>
 <section className="project-framework tradeoff-section shell" id="decisions"><div className="section-intro"><p className="kicker">Decisions & tradeoffs</p><h2>Modernize what created friction. Protect what already worked.</h2></div><div className="tradeoff-grid">{d.tradeoffs.map(([type,choice])=><article key={type}><span>{type}</span><p>{choice}</p></article>)}</div></section>
 <section className="project-framework launch-view" id="launch"><div className="shell"><div className="section-intro"><p className="kicker">Launch & change management</p><h2>A controlled rollout reduced customer and operational risk.</h2></div><ol>{d.launch.map(([stage,action],i)=><li key={stage}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{stage}</h3><p>{action}</p></div></li>)}</ol></div></section>
 <section className="project-framework shell" id="measurement-dashboard"><div className="section-intro"><p className="kicker">Success measurement</p><h2>Evidence is labeled by confidence.</h2></div><div className="project-metrics">{d.metrics.map(([type,value])=><article key={type}><span>{type}</span><p>{value}</p></article>)}</div></section>
 <section className="project-framework backlog-section shell" id="backlog"><div className="section-intro"><p className="kicker">Next iteration backlog</p><h2>The roadmap follows evidence, not novelty.</h2></div><div className="backlog-table">{d.backlog.map(([priority,item,why],i)=><article key={item}><b>{String(i+1).padStart(2,"0")}</b><span className={`priority ${priority.toLowerCase()}`}>{priority}</span><h3>{item}</h3><p>{why}</p></article>)}</div></section>
 </>}
