import Link from "next/link";

const principles = ["Customer-first thinking", "Business impact before features", "Operational simplicity", "Data-informed decisions", "Cross-functional alignment", "Sustainable solutions"];
const discovery = ["Business request", "Discovery meetings", "Current-state review", "Customer pain points", "Operational constraints", "Technical feasibility", "Opportunity assessment", "Requirements definition"];
const launch = ["Requirements", "Design review", "Development", "QA", "Internal readiness", "Customer communication", "Rollout", "Monitoring", "Iteration"];
const stakeholders = [
  ["Customers", "Clear, dependable experience", "Discovery · validation"], ["Customer service", "Fewer questions and exceptions", "Discovery · readiness"],
  ["Production", "Stable, accurate fulfillment", "Requirements · QA"], ["Sales", "Customer value and growth", "Opportunity · rollout"],
  ["Leadership", "Impact, risk, and focus", "Prioritization · decisions"], ["Compliance", "Accurate requirements", "Definition · QA"],
  ["Technical teams", "Feasible, maintainable delivery", "Scoping · implementation"],
];
const scorecard = [
  ["Customer impact", "20%"], ["Customer friction", "15%"], ["Business / compliance risk", "15%"], ["Revenue opportunity", "10%"], ["Strategic alignment", "10%"],
  ["Support volume", "10%"], ["Technical complexity", "-8%"], ["Development effort", "-7%"], ["Maintenance burden", "-5%"],
];

export default function HowIWork(){return <main id="top">
  <a className="skip-link" href="#operating-system">Skip to operating system</a>
  <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">A</span><span>Andrew</span></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/">Projects</Link><Link href="/how-i-work" aria-current="page">How I Work</Link><a href="#measurement">Measurement</a></nav><a className="nav-cta" href="mailto:andrewjaebok@gmail.com">Contact ↗</a></header>
  <section className="work-hero shell" id="operating-system"><p className="eyebrow">My operating system</p><h1>From ambiguous request to measurable operational improvement.</h1><p>I connect customer needs, business priorities, operational realities, and technical constraints so teams can make better decisions and launch changes that last.</p><div className="work-hero-proof"><span><b>Discover</b> the real problem</span><span><b>Decide</b> with shared criteria</span><span><b>Deliver</b> with controlled risk</span><span><b>Improve</b> with evidence</span></div></section>

  <section className="work-section shell"><div className="work-heading"><p className="eyebrow">Operating philosophy</p><h2>Principles that keep the work practical.</h2></div><div className="principle-grid">{principles.map((p,i)=><article key={p}><b>{String(i+1).padStart(2,"0")}</b><span>{p}</span></article>)}</div></section>

  <section className="work-section dark-framework"><div className="shell"><div className="work-heading"><p className="eyebrow">Discovery framework</p><h2>Define the problem before defining the solution.</h2></div><ol className="process-flow">{discovery.map((step,i)=><li key={step}><b>{String(i+1).padStart(2,"0")}</b><span>{step}</span></li>)}</ol><p className="framework-note">Output: a shared problem definition, documented constraints, success criteria, and requirements the team can test.</p></div></section>

  <section className="work-section shell"><div className="work-heading split-heading"><div><p className="eyebrow">Prioritization framework</p><h2>Make tradeoffs visible.</h2></div><p>Requests are scored by value and risk, then balanced against complexity and long-term cost. The score supports judgment, it does not replace it.</p></div><div className="priority-layout"><div className="scorecard">{scorecard.map(([name,weight])=><div key={name}><span>{name}</span><b>{weight}</b></div>)}</div><div className="priority-matrix" aria-label="Impact and effort matrix"><span className="matrix-label top">Higher impact</span><article className="do-now"><b>Do now</b><small>High impact · Lower effort</small></article><article className="plan"><b>Plan deliberately</b><small>High impact · Higher effort</small></article><article className="quick"><b>Quick wins</b><small>Lower impact · Lower effort</small></article><article className="defer"><b>Defer or decline</b><small>Lower impact · Higher effort</small></article></div></div></section>

  <section className="work-section stakeholder-section"><div className="shell"><div className="work-heading"><p className="eyebrow">Stakeholder management</p><h2>Bring each voice in when it can change the outcome.</h2></div><div className="stakeholder-map"><div className="stakeholder-center"><b>Product Operations</b><span>Shared context · decisions · follow-through</span></div>{stakeholders.map(([name,goal,when])=><article key={name}><h3>{name}</h3><p>{goal}</p><span>{when}</span></article>)}</div></div></section>

  <section className="work-section shell"><div className="work-heading"><p className="eyebrow">Decision framework</p><h2>Evaluate the whole system, not one screen.</h2></div><div className="decision-ring"><div><b>01</b><span>Problem definition</span></div><div><b>02</b><span>Business value</span></div><div><b>03</b><span>Customer impact</span></div><div><b>04</b><span>Operational impact</span></div><div><b>05</b><span>Technical constraints</span></div><div><b>06</b><span>Maintenance cost</span></div><div><b>07</b><span>Future scalability</span></div></div><div className="tradeoff-example"><strong>Example decision pattern</strong><span><b>Change:</b> simplify navigation and add self-service tools.</span><span><b>Preserve:</b> working backend logic and familiar production terminology.</span><span><b>Defer:</b> full platform replacement until its value outweighs migration risk.</span></div></section>

  <section className="work-section launch-section"><div className="shell"><div className="work-heading"><p className="eyebrow">Launch & change management</p><h2>Reduce risk at every handoff.</h2></div><ol className="launch-flow">{launch.map((step,i)=><li key={step}><b>{i+1}</b><span>{step}</span><small>{["Align scope","Confirm direction","Build safely","Test workflows","Prepare teams","Set expectations","Release deliberately","Watch signals","Improve"][i]}</small></li>)}</ol></div></section>

  <section className="work-section shell" id="measurement"><div className="work-heading"><p className="eyebrow">Success measurement</p><h2>Separate proof from promising signals.</h2></div><div className="measurement-dashboard"><article><span>01</span><h3>Verified outcomes</h3><p>Confirmed business results tied to trusted data.</p></article><article><span>02</span><h3>Operational improvements</h3><p>Less manual effort, fewer exceptions, clearer workflows.</p></article><article><span>03</span><h3>Customer feedback</h3><p>Observed or reported changes in ease and confidence.</p></article><article><span>04</span><h3>Directional evidence</h3><p>Traffic, adoption, or order signals without overclaiming causation.</p></article><article><span>05</span><h3>Future KPIs</h3><p>Instrumentation needed to measure conversion and efficiency.</p></article></div></section>

  <section className="work-section continuous-section"><div className="shell"><div className="work-heading"><p className="eyebrow">Continuous improvement</p><h2>Launch creates the next learning loop.</h2></div><div className="improvement-loop">{["Collect feedback","Review evidence","Prioritize","Iterate","Manage technical debt","Update roadmap"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><Link className="primary-button" href="/#work">See this approach in the case studies</Link></div></section>
  <footer className="site-footer shell"><div><span className="brand-mark">A</span><strong>Andrew</strong></div><p>Digital operations · Product transformation</p><a href="#top">Back to top ↑</a></footer>
</main>}
